---
- name: Deploye a jar file
  host: slave
  remote_user: root
  become: yes
  tasks: 
    - name: copy the file
      copy:
        src: /var/lib/jenkins/workspace/jarfile/target/spring-boot-hello-world-example-0.0.1-SNAPSHOT.jar
        dest: /home/pavan
        